version: '2'

services:
  mariadb:
    image: 'mariadb:10'
    environment:
      - MYSQL_ROOT_PASSWORD=picMesicFekcagVesItejzeic
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=ThwefWockKouptom5dreykGhop

  app:
    image: 'php:fpm-alpine'
    depends_on:
      - mariadb
    ports:
      - 3000:9000
    volumes:
      - ./www/:/var/www/html
