version: '3'
# ************ README ****************
# Reads env vars from .env
# Requires docker-compose version 1.7+
# ************************************

services:
  # Webserver
  app:
    container_name: ${DOCKER_COMPOSE_APP_NAME}-httpd
    image: benyanke/nginx-php7-fpm:latest
    ports:
      - ${PORT_APP:-8080}:80
    # user: "${UID}:${GID}"
    expose:
      - 80
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
      # DB env bootstrap flags - by default, they're one
      - CMD_DIR=/var/www
      - RUN_PERMISSION_FIX=${SETUP_DEV_ENV:-1}
      - RUN_COMPOSER=${SETUP_DEV_ENV:-1}
      - RUN_WEBPACK=${SETUP_DEV_ENV:-1}
      - RUN_MIGRATIONS=${SETUP_DEV_ENV:-1}
      - RUN_DB_SEED=${SETUP_DEV_ENV:-1}
      - RUN_VENDOR_PUBLISH=${SETUP_DEV_ENV:-1}
    volumes:
      - ./www/laravel:/var/www/
      - ./docker/nginx/sites:/etc/nginx/sites-enabled
      - ./docker/nginx/logs:/var/log/nginx/
      - ./docker/nginx/snippets:/etc/nginx/snippets
      - ./docker/nginx/fpm/pool.d:/etc/php/7.2/fpm/pool.d
      - ./docker/nginx/startup.sh:/opt/startup/startup.sh
      - ./docker/.tmp/composer/cache:/root/.composer/cache
      - ./docker/nginx/supervisor/conf.d:/etc/supervisor/conf.d
      # - ./docker/.tmp/npm/cache:[npm-cache-dir-here]
    links:
      - db:${DB_HOST}
      - redis:${REDIS_HOST}
    networks:
      - laravel-network
    depends_on:
      - db
      - redis
      - queue-daemon
      - phpmyadmin
    # env_file:
    #  - .local.env

  db:
    container_name: ${DOCKER_COMPOSE_APP_NAME}-db
    image: mariadb:latest
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/.tmp/db-data:/var/lib/mysql
    networks:
      - laravel-network

  redis:
    container_name: ${DOCKER_COMPOSE_APP_NAME}-redis
    image: vcarreira/redis
    expose:
      - 6379
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --appendonly yes
    volumes:
      - ./docker/redis:/data
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:edge
    container_name: ${DOCKER_COMPOSE_APP_NAME}-pma
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_PORT=${DB_PORT}
    ports:
      - ${PORT_PMA:-8081}:80
    links:
      - db:${DB_HOST}
    networks:
      - laravel-network
    depends_on:
      - db

  queue-daemon:
    container_name: ${DOCKER_COMPOSE_APP_NAME}-queue-daemon
    build:
      context: ./docker/laravel-queue
      dockerfile: laravel-queue.dockerfile
    volumes:
      - ./www:/var/www
      - ./docker/laravel-queue/logs:/var/log/supervisor
    links:
      - db:${DB_HOST}
      - redis:${REDIS_HOST}
    networks:
      - laravel-network

  # one-off containers
  # call docker-compose rm -a -f after docker-compose up to remove all one-off containers
  # or simply use the alias dcup
  artisan:
    image: vcarreira/artisan
    volumes:
      - ./www/laravel:/var/www
    links:
      - db:${DB_HOST}
      - redis:${REDIS_HOST}
    networks:
      - laravel-network
    depends_on:
      - db
      - redis

  # This isn't fully there - keeping it so we can get it added later
  phpunit:
    image: vcarreira/phpunit
    volumes:
      - ./www/:/var/www
    links:
      - db:${DB_HOST}
      - redis:${REDIS_HOST}
    networks:
      - laravel-network
    depends_on:
      - db
      - redis

  # This isn't fully there - keeping it so we can get it added later
  phpspec:
    image: vcarreira/phpspec
    volumes:
      - ./www:/var/www
    links:
      - db:${DB_HOST}
      - redis:${REDIS_HOST}
    networks:
      - laravel-network

  # This is probably not needed anymore - composer is installed in the app container
  composer:
    image: vcarreira/composer
    volumes:
      - ./www/laravel:/var/www
      # - ./docker/.tmp/composer/cache:/root/.composer/cache
      - ./docker/.tmp/composer:/root/.composer
    networks:
      - laravel-network

  # This isn't fully there - keeping it so we can get it added later
  node:
    image: vcarreira/node
    volumes:
      - ./www/laravel:/var/www
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
