#!/bin/bash
alias dc-up="sudo docker-compose up -d nginx mysql redis"
alias dc-down="sudo docker-compose down"
alias dc-art="sudo docker-compose run --rm artisan"
alias dc-artisan="sudo docker-compose run --rm artisan"
alias dc-phpunit="sudo docker-compose run --rm phpunit"
alias dc-phpspec="sudo docker-compose run --rm phpspec"
alias dc-composer="sudo docker-compose run --rm composer"
alias dc-node="sudo docker-compose run --rm node node"
alias dc-gulp="sudo docker-compose run --rm node gulp"
alias dc-npm="sudo docker-compose run --rm node npm"
alias dc-bower="sudo docker-compose run --rm node bower"

alias dc-backup="sudo docker-compose up -d mysql-backup"
alias dc-adminer="sudo docker-compose up -d adminer"
alias dc-queue="sudo docker-compose up -d queue-daemon"
